### PR TITLE
Added overrides support

### PR DESCRIPTION
**Pull request by glebsexy**
Hi there, I was working on a similar plugin and thought I would as well contribute to this one. I added a lot of code but the basic functionality stays the same.

## Overrides support

The plugin recursively checks properties children of frames that are going to be replaced. If properties are different, it overrides them within the instance. It checks only overridable properties, so for example position of nodes within cannot be edited so it doesn't check it.

Text overrides work as well, even for properties which are applied to parts of text, however they slow the plugin down as it has to check and override properties on every single character. But it takes much less time than finding an instance in a large file.

## Other changes

- Now master components can be used as reference as well
- Slightly refactored the original code for consistency and readability
- Added a lot of comments
- Updated the readme, you can update plugin description in the store with it

### CODE REVIEW

**Comment by glebsexy** [comment]
Oops, I didn't see #5

**Comment by renancamm** [comment]
Hi @zyumbik , thanks for the contribution!

I've just merged #5 to master. Do you mind to evaluate if you override approach is better?

**Comment by glebsexy** [comment]
That's great! I don't know if this has any advantages over #5. Does #5 apply overrides for mixed-style text layers too? If yes, my solution is probably just the same. :)

**Review by bespoyasov — APPROVED** [review]

**Comment by bespoyasov** [comment]
> Does #5 apply overrides for mixed-style text layers too?

No, it doesn't :–) 

I think we can revert my PR and replace it with this one, @renancamm, @mikeozornin.

**Pull request merged**
